### ISSUE TITLE
Gitbook 的安装应该装哪个包？

### ISSUE THREAD

**Issue by WindWood** [chengweiv5/gitbook#1]
在[官网的手册](https://github.com/GitbookIO/gitbook/blob/master/docs/setup.md) 上的安装步骤是 `npm install gitbook-cli -g`，而你的教程上是 `npm install gitbook -g`，查了一下，[gitbook 包](https://www.npmjs.com/package/gitbook)和 [gitbook-cli 包](https://www.npmjs.com/package/gitbook-cli)还是不一样的。
那么到底应该装哪个包呢？

**Comment by chengweiv5** [comment]
@WindWood 请以官方文档为准，我的教程很久没有更新了 :cry:

**Comment by WindWood** [comment]
谢谢回复！也谢谢你的书，事实上我很长一段时间参考它，它确实写得很好。

**Comment by chengweiv5** [comment]
@WindWood 谢谢，希望它对你的帮助超过给你带来的困扰。
