### ISSUE TITLE
关于插件multipart和Search Pro的一些问题

### ISSUE THREAD

**Issue by OumCc** [chengweiv5/gitbook#3]
你好，我安装了multipart之后还是不能自动生成目录编号。

```
    "plugins": [
        "multipart"
    ],
```

我直接在book.json中写上了上面一句，然后用`gitbook install`安装的，结果没反应，还是不能自动编码。难道一定要使用`npm install gitbook-plugin-multipart`安装才行？
另外，其实这两个命令有区别吗？

还有一点想请教请教，Search Pro插件的安装好像有点问题，总是装不上，不知大神是否有办法？

**Comment by chengweiv5** [comment]
已经有一两年没有看 gitbook 了，我上次看的时候 multipart 已经不能和新版的 gitbook 一起工作了，只能你自己再看看了 😢

**Comment by OumCc** [comment]
O(∩_∩)O好的，谢谢，暂时还是没有弄成功，暂时放放。/(ㄒoㄒ)/~~
