### ISSUE TITLE
请问如何将gitbook发布到域名的文件夹下?

### ISSUE THREAD

**Issue by wangluzhou** [chengweiv5/gitbook#7]
我看教程上说域名绑定只能是一个合法的域名，不能是域名下的某个地址，例如：chengweiyang.cn/test, chengweiyang.cn/test/content。但是我看到您的gitbook是放在主域名的子文件下的，请问这是如何操作的？谢谢!

**Comment by chengweiv5** [comment]
chengweiyang.cn 是 HOST，后面的是 URI，也就是目录。
